### ISSUE TITLE
update kovan modules in the documentation

### ISSUE THREAD

**Issue by juanpcapurro** [SetProtocol/set-v2#5]
First of all, sorry if it's the wrong repository, I couldn't easily find where the sources for the documentation are hosted

I was playing around with the protocol's modules today and couldn't find the SingleIndex module in the documentation.

So I asked the Controller contract for its modules and realized the doc's list of deployed contracts doesn't match the whitelisted modules in the contract.

Namely, this modules are not listed in the docs, but are registered in the contract

    0x0b757bf5c4f72830b5a8bc47abe7f02c350398de
    0x1104c573e3f2455c6a19ba79ab240d18ac4ec22e
    0x13ed6288efcddfcccdab33ef56f173e6681ff334
    0x1a8c29f82a87bd08394a20f972b6bea05e4ea2a4
    0x357d08f552101a89f111cf5601d41f68ae51c3ec
    0x3e0c955d216a58c76167a3c8885f2e58e2d07f7d
    0x3ebe128fda0f1cfcd5d4beff34422ab39d2ca573
    0x4a1f7c3728c9d44b9cb0fd267f94db2c65a1b0f1
    0x6bd77ab7abf56931d4add822cf45f3a55cd028f7
    0x75e1d0b471914cb8bff8e088e9022476afe4516a
    0x79e3429bf42c1b4ef9f8677408dacba0aefb4604
    0x82f2cdbd4ab3d109c4ad3eeee5c6fe73794fe84b
    0x8398f4710d35c8f15a7e4eced3e7b6a0e909d019 (this seems to be the SingleIndex module)
    0x84b112aa139f6048b64f26e05ce88a6dd1ea7a52
    0x8bd721bd013cf3350eca7455b6eb51dc22581b57
    0x93b28fbd71b5534a44f8ab4b6ee7769456f9625c
    0x93faa2ad08bbdc2355ad8e99a03d7a8f80376793
    0x94c2cd5d11d756e3356878470788456114eed8e5
    0xc2d072187721143d556af16131e137ddafbca014
    0xca464e0804ddffcf13420fb44a0a117e31ab910d
    0xd2a0b0e3334f46ded86f6bba3fc92b785ab0cd12
    0xd33ec708e608c02954cd9f54a6dcc51c8faab6ac
    0xe100732364c23ad12f0579db3d8f65eccf84c4bb

This modules are only listed in the docs, and are not present in the contract

    0x071126fbb52f987c2e48c6e395afa655529e6efc
    0x1c3d24cc87994e9f00960e9106a9e2ec7e89e38a
    0x266b9393b0d2a385e8d32d84084b9afbf80b30b9
    0x28a87dcca3322f90b3a4ce80cee499869efdbf11
    0x9048278ca7e874f9338e4898c436ab07aa454701
    0xa37f4c5a7ad72eea9034195b75e7498c7ed1d4e3
    0xb24f7367ee8efcb5eabe4491b42fa222ec68d411
    0xb38afb233d0667dd46fa81848536d8d08bddbf22
    0xda10d6cd31f1ba4ba9e0bab85bfe58ccfbaa19b0
    0xdfea02f2824ee177733d6f108005e95c85d1d4be

**Comment by richardliang** [comment]
Thanks. We should clean up a lot of those addresses on Kovan, those were test deployments
