### ISSUE TITLE
TradeModule configuration on Kovan

### ISSUE THREAD

**Issue by juanpcapurro** [SetProtocol/set-v2#6]
I'm currently trying to create a rebalanceable Set on Kovan
I was able to create a set, add the BasicIssuance and Trade modules, mint and redeem.

But when trying to trade, it seems like the only available exchange integration for the Trade module is the OneInchExchangeAdapter (added in tx: https://kovan.etherscan.io/tx/0x7088056d42dd9885a74b8f59be7d76e96aa3f8216e0935500dc35f9e190065f5)

Trade transactions revert with a message of Not One Inch Swap Function (tx 0xd27a7543404e7f171d7479c6391a4f832b49f59f7801b91c230099a490a669af)

Is it possible that the exchange integration isn't configured correctly on Kovan?

**Comment by richardliang** [comment]
Hey, you would have to use mainnet in this case, there isn't a valid 1inch deployment on Kovan https://docs.tokensets.com/protocol/untitled

**Comment by juanpcapurro** [comment]
@richardliang is there any documentation on what should I send on the `_data` parameter for `trade`? 

I'm doing the same call on mainnet (forked via ganache) and I get the same error

**Comment by richardliang** [comment]
Yeah, for 1inch in particular, _data is just the calldata from 1inch's API. One thing that is weird is that to call 1inch's API, you'd need to pass in the total notional of the component you want to trade, but the minReceiveQuantity and sendQuantity params are individual units

E.g. https://api.1inch.exchange/v1.1/swapQuote?fromTokenSymbol=REPV2&toTokenSymbol=UNI&amount=595616045297018431&fromAddress=0x9F295d05bAeE0E95F52aC1db0C2bDc26A226e4BB&slippage=1&disableEstimate=true

**Comment by juanpcapurro** [comment]
I'll close this issue since @richardliang was of great help and I've been able to figure it out,

for anyone seeing this in the future, I'd like to clarify:

- to the `trade` method, you should pass the amount of _units_ you want to decrease/increase the composition by
- to 1Inch's API, you should send what richard refers to as the _total notional_, which is the amount of the component that'll actually be traded in the exchange, which is `unitsToTrade * totalSupply()`
